// src/routes/asp/+page.svelte
<script>
  let { data } = $props();
  let current = $state();
  const names = {
    bio: "Biology",
    chem: "Chemistry",
    econs: "Economics",
    eng: "English",
    gov: "Government",
    phy: "Physics",
  };
</script>

<main class="main">
  <h2 class="header">Post-UTME Subjects</h2>
  <div class="container">
    {#each data.subjects as subject}
      <a
        href={`/asp/${subject}`}
        class={`course selector ${current === subject ? "selected" : ""}`}
        onclick={(e) => {
          e.preventDefault();
          current = subject;
        }}
      >
        {names[subject] ?? subject}
      </a>
    {/each}
  </div>
  {#if current}
    <footer>
      <a href={`asp/${current}`}
        ><button class="footerButton">Get Started</button></a
      >
    </footer>
  {/if}
</main>

<style>
  .container {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    min-height: 100vh;
    color: #fff;
    font-family: sans-serif;
    width: 80vw;
    position: relative;
    margin-top: 50px;

    margin-bottom: 50px;
  }
  .faculties {
    display: flex;
    align-items: center;
    justify-content: center;
    flex-direction: row;
    max-width: 100vw;
    height: 40vh;
    overflow: hidden;
  }
</style>

// app/asp/page.jsx
import Link from "next/link";
import styles from '@/app/page.module.css';

export const metadata = {
  title: "post utme,"
}

export default function Home() {
 
    return (
        <div>
            <main className={styles.main}>
            <h4>Good Luck on your exams</h4>
                <Link href='/asp/courses/econs/quiz'><button className="course selector">Economics</button></Link>
                <Link href={`/asp/courses/gov/quiz`}><button className="course selector">Government</button></Link>
               <Link href={`/asp/courses/eng/quiz`}><button className="course selector">English</button></Link> 
               <Link href={`/asp/courses/bio/quiz`}><button className="course selector">Biology</button></Link> 
               <Link href={`/asp/courses/phy/quiz`}><button className="course selector">Physics</button></Link> 
               <Link href={`/asp/courses/chem/quiz`}><button className="course selector">Chemistry</button></Link> 
            </main>
              
            <footer>
                <Link href={`/app`}><button className="footerButton"><h5>Change Mode</h5></button></Link>
            </footer>
        </div>
    )
}
